# Generated by Django 5.2.6 on 2025-10-24 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='biometric_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='budget_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='date_format',
            field=models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='MM/DD/YYYY', max_length=10),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='monthly_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='notification_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='report_format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('Excel', 'Excel')], default='PDF', max_length=10),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='start_of_week',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=10),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='transaction_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='weekly_reports',
            field=models.BooleanField(default=True),
        ),
    ]
