# Generated by Django 5.2.6 on 2025-09-21 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for the category (e.g., 'Groceries', 'Freelance Income')", max_length=100)),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', help_text='Whether this category is for incoming or outgoing money', max_length=10)),
                ('color', models.CharField(default='#000000', help_text="HEX color code for UI display (e.g., '#FF5733')", max_length=7)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier for frontend (e.g., 'restaurant', 'flight')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who owns this category', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
