# Generated by Django 5.2.6 on 2025-10-15 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('transactions', '0002_auto_20251015_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='CFA', help_text='Currency code (e.g., USD, EUR, GBP)', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(help_text='Category this transaction belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='categories.category'),
        ),
    ]
