# Generated by Django 5.2.6 on 2025-10-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_currency_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, GBP)', max_length=3),
        ),
    ]
