# Generated by Django 5.2.7 on 2026-01-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_is_recurring_transaction_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='next_run_date',
            field=models.DateField(blank=True, help_text='Next date this recurring transaction should occur', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
    ]
